### ISSUE TITLE
[EPIC] Changer la façon de générer les textes d'invitation liés au contexte

### ISSUE THREAD

**Issue by SalmaBennani** [betagouv/rdv-insertion#1177]
## 🚀 Objectif de l'EPIC

Mettre à jour nos Contextes actuels pour faciliter la personnalisation sans rentrer dans le cas par cas.

## ❓ Définition du problème

Nous avons décidé de nous élargir au monde de l'insertion. Nous allons avoir de plus en plus de type de structures différentes qui vont avoir des vocabulaires et des besoins différents au moment des invitations. 

Nos invitations actuelles ne sont pas paramétrables, il faudrait pouvoir les rendre personnalisables un minimum pour faciliter l'appel à la prise de rdv tout en s'assurant du respect des valeurs de rdv-insertion.

## 🏅 Définition de la solution proposée

Pouvoir mettre en place des variables sur certains contextes pour permettre la personnalisation.

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/rdv-insertion/issues/1180
- [ ] https://github.com/betagouv/rdv-insertion/issues/1181
- [ ] https://github.com/betagouv/rdv-insertion/issues/1182
- [ ] https://github.com/betagouv/rdv-insertion/issues/1184
- [ ] https://github.com/betagouv/rdv-insertion/issues/1185
- [ ] https://github.com/betagouv/rdv-insertion/issues/1160
- [ ] https://github.com/betagouv/rdv-insertion/issues/1161
```

**Comment by rprebot** [comment]
Rappel : on va vérifier via cette EPIC que la mention à la sanction est bien paramétrée pour les contextes concernées. 

Les contextes concernées sont : 
- rdv accompagnement RSA
- rdv accompagnement demandeur emploi
- rdv signature CER
- entretien main tendue
