### ISSUE TITLE
[Créer plusieurs catégories d'usager] Ajout d'un dropdown de sélection des tags

### ISSUE THREAD

**Issue by Michaelvilleneuve** [betagouv/rdv-insertion#1300]
Afin de finaliser l'EPIC des tags et suite au retour des premiers tests il reste à : 

- [ ] Rajouter un dropdown d'autocomplete lors de la création d'un tag sur la catégorie. Ce dropdown devra afficher les tags existant dans le département
- [ ] Renommer "Catégories d'usagers" en "Tags" pour être plus explicites
- [ ] Faire en sorte que les filtres fasse un "AND" plutôt qu'un "OR"
