### ISSUE TITLE
[EPIC] Créer une interface bénéficiaire  

### ISSUE THREAD

**Issue by rprebot** [betagouv/rdv-insertion#1395]
<img width="659" alt="Capture d’écran 2023-09-19 à 10 24 26" src="https://github.com/betagouv/rdv-insertion/assets/5745148/a356de1a-ac45-4c81-b85f-d097005cd3f3">

## 🚀 Objectif de l'EPIC

Créer une interface bénéficiaire pour permettre aux bénéficiaires d'être d'avantage acteur de leurs parcours, en ayant accès à l'offre d'insertion dont ils peuvent profiter, et à leurs informations de parcours

## ❓ Définition du problème

- L'offre d'insertion sur un territoire  est pléthorique (une multitude d'acteurs, associatifs, SIAE, etc.) mais la rencontre avec les personnes en insertion ne se fait pas suffisamment par manque de connaissance

- Une fois engagée dans son parcours, une asymétrie d'informations se crée entre le bénéficiaire et le professionnel qui l'accompagne : la gestion de son parcours lui "échappe" (ex : il ne peut pas consulter ni modifier ses informations de parcours ou prendre rdv en autonomie) 

## 🏅 Définition de la solution proposée

Créer une vue usager (cf capture d'écran) avec les blocs fonctionnels suivants : 
- mes infos : en particulier, permet de garder les infos de contact à jour
- mes orgas : avoir en visibilité l'ensemble des acteurs avec qui je peux prendre directement RDV
- mon parcours (diag, CER, historique des RDV) : diminuer les asymétries d'informations entre bénéficiaire et agent
- mon référent : pouvoir prendre rdv à tout moment avec mon (ou mes) référents

**📊 Qualification de l'impact avec la méthode RICE**

Reach - aujourd'hui : 60 000 bénéficiaires dans l'application (mais on ne sait pas s'ils sont tous actifs)

Impact - 
amélioration sur la prise de RDV en autonomie & et pour permettre des mises en relation entre usager et acteurs de l'insertion
2 : l'EPIC améliore l'existant et permettra de créer de nouveaux usages

Confidence - 2 
_- On a un doute sur le fait que le bénéficiaire se saisisse vraiment de ces features_ 

Effort  : L (1 sprint)
_L si les autres briques nécessaires (bloc parcours + offre d'insertion) sont déjà développées_ 

##  0️⃣  Tâches prioritaires dans une V0 de l'EPIC

_La V0 de l'EPIC est notre prototype : elle va nous servir à savoir si le bénéficiaire a un intérêt pour cette interface_

- [ ] Créer un système d'authentification pour l'usager sur rdv-inseriton
- [ ] Créer une vue avec les informations personnelles (nom, prénom, contact) et les informations du référent
- [ ] Envoyer automatiquement un SMS redirigeant vers la page personnelle une fois le RDV d'orientation effectuée + référent assigné 

_Reprise des tickest créés précédemment par Amaury dans l'EPIC #1084_
#1085
#1086
#1087
#1088

##  🎯 Tâches pour la solution cible

_Si tout était possible sans contrainte de temps et de dev, quelles features on aimerait rajouter, pour solutionner le problème ?_

- [ ] #numéro de l'issue

**Comment by amaurydubot** [comment]
Je ferme cette EPIC issue de l'atelier séminaire de Nantes car rapatriée dans le product backlog : https://www.notion.so/gip-inclusion/New-Cr-er-une-interface-b-n-ficiaire-e22dce284a774f12aaf96c3e26c0a435?pvs=4
