### ISSUE TITLE
[EPIC] Mettre en place une marque unique RDV-Insertion

### ISSUE THREAD

**Issue by rprebot** [betagouv/rdv-insertion#1409]
https://docs.google.com/presentation/d/17ihyfgpRy6QZDpHkBBncfRDW7mrBCa3pohYH0QH8Nn8/edit#slide=id.p

## 🚀 Objectif de l'EPIC

Vision usager : Améliorer le taux de prise en autonomie en améliorant le parcours de prise de RDV pour les utilisateurs avec une marque unique RDV-Insertion
Vision agent : Permettre de former plus rapidement les agents

## ❓ Définition du problème

Pour les usagers :
- perte (non quantifiée) lors de la prise de RDV en autonomie, du fait d'une incompréhension d'avoir un SMS/mail d'invitation brandé RDV-I, et une interface brandée RDV-S

Pour les agents : 
- besoin d'un temps de formation long pour expliquer la double interface rdv-s / rdv-i

## ⚠️ Risque potentiel à anticiper

- 5517 usagers (sur 62000) sont présents sur des orgas rdv-i et rdv-s 
- 207 agents sont présents sur des orgas rdv-i et rdv-s

##  0️⃣  Tâches prioritaires dans une V0 de l'EPIC

- [ ] Rebrander les mails et sms partant de RDV-S et les signer RDV-I
- [ ] Réserver un nom de domaine "www.app.rdv-insertion.fr" 
- [ ] Dupliquer rdv-s sur "app.rdv-insertion.fr" pour l'utilisation rdv-i
- [ ] Rendre possible la création du compte depuis rdv-insertion
- [ ] Créer un espace personnel agent sur rdv-insertion pour configurer le compte
- [ ] Positionner des CTA depuis RDV-Insertion pour : voir le calendrier et fixer une plage d'ouverture, créer des motifs, créer des lieux

##  🎯 Tâches pour la solution cible

_Si tout était possible sans contrainte de temps et de dev, quelles features on aimerait rajouter, pour solutionner le problème ?_

- [ ] #numéro de l'issue

**Comment by amaurydubot** [comment]
Je ferme car les orientations produits + les développements #1861 et #1974 nous ont fait aller vers autre chose.
