### ISSUE TITLE
[Statistiques] Améliorer les statistiques

### ISSUE THREAD

**Issue by rprebot** [betagouv/rdv-insertion#914]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/rdv-insertion/issues/640
- [ ] https://github.com/betagouv/rdv-insertion/issues/656
- [ ] https://github.com/betagouv/rdv-insertion/issues/581
- [ ] https://github.com/betagouv/rdv-insertion/issues/1179
- [ ] https://github.com/betagouv/rdv-insertion/issues/1178
- [ ] https://github.com/betagouv/rdv-insertion/issues/1022
- [ ] https://github.com/betagouv/rdv-insertion/issues/1023
- [ ] https://github.com/betagouv/rdv-insertion/issues/1245
- [ ] https://github.com/betagouv/rdv-insertion/issues/1246
- [ ] https://github.com/betagouv/rdv-insertion/issues/1261
```

**Comment by Holist** [comment]
Avec le champ `created_by` au niveau des participations (https://github.com/betagouv/rdv-solidarites.fr/pull/3486), on pourra également ajouter des statistiques pour les rdv collectifs.

**Comment by ClaireCasu** [comment]
@amaurydubot on pourrait ajouter ici l'amélioration de l'export csv pour les rdv co !

**Comment by amaurydubot** [comment]
> @amaurydubot on pourrait ajouter ici l'amélioration de l'export csv pour les rdv co !

Yes normalement avec les #1245 et les #1246, un département comme les Pyrénées-Atlantiques aura en v0 tout ce qu'il faut pour faire ses statistiques FT (dans l'export ils pourront identifier le bon motif et le rendez-vous collectif de telle date, tel jour). NB : il leur restera du traitement manuel après export c'est sûr mais au moins ils pourront suivre les stats de leurs différents rendez-vous co sans avoir à faire le croisement complexe de l'export RDV-S et de l'export RDV-I.

**Comment by amaurydubot** [comment]
Je ferme cet EPIC stats car toutes les tâches listées supra ont été réalisées.
